# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }

    body_listener:
        enabled: true
        default_format: json
        decoders:
            json: fos_rest.decoder.json
        throw_exception_on_unsupported_content_type: true

    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: constraintViolationList

    exception:
        enabled: true
        map_exception_codes: true

#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
