services:
    Google_Client:
        class: Google_Client
        calls:
            - [setDeveloperKey, ['%google.api_key%']]
            - [setClientId, ['%google.client_id%']]
            - [setClientSecret, ['%google.client_secret%']]
