framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'support@ufit.io'
        headers:
            from: 'uFit <support@ufit.io>'
            bcc: 'ufit@ufit.io'
