framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            subscription: '%env(MESSENGER_TRANSPORT_DSN_SUBSCRIPTION)%'
            vendor: '%env(MESSENGER_TRANSPORT_DSN_VENDOR)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

            email:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_EMAIL)%'
                retry_strategy:
                    max_retries: 10
                    delay: 5000
                    multiplier: 1
                    max_delay: 0

        routing:
            'App\Program\Message\ProgramCreatedEvent': vendor
            'App\Program\Message\ProgramUpdatedEvent': vendor
            'App\Program\Message\ProgramDeletedEvent': vendor
            'App\Program\Message\ProgramAssetCreatedEvent': vendor
            'App\Program\Message\ProgramAssetDeletedEvent': vendor
            'App\Program\Message\ProgramAssignmentCreatedEvent': vendor
            'App\Program\Message\ProgramAssignmentDeletedEvent': vendor
            'App\Program\Message\ProgramAssignmentExpiredEvent': vendor

            'App\Subscription\Message\SubscriptionCreatedEvent': subscription

            'Symfony\Component\Mailer\Messenger\SendEmailMessage': email
