framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            subscription: '%env(MESSENGER_TRANSPORT_DSN_SUBSCRIPTION)%'
            vendor: '%env(MESSENGER_TRANSPORT_DSN_VENDOR)%'
            payment: '%env(MESSENGER_TRANSPORT_DSN_PAYMENT)%'
            sync: 'sync://'
            void: 'in-memory://'
            # failed: 'doctrine://default?queue_name=failed'

            email:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_EMAIL)%'
                retry_strategy:
                    max_retries: 10
                    delay: 5000
                    multiplier: 1
                    max_delay: 0

        routing:
            'App\Customer\Message\CustomerCreatedEvent': void

            'App\Payment\Message\InvoicePaidEvent': payment
            'App\Payment\Message\PaymentCreatedEvent': payment
            'App\Payment\Message\PaymentUpdatedEvent': void

            'App\Program\Message\ProgramCreatedEvent': void
            'App\Program\Message\ProgramUpdatedEvent': void
            'App\Program\Message\ProgramDeletedEvent': void
            'App\Program\Message\ProgramAssetCreatedEvent': void
            'App\Program\Message\ProgramAssetDeletedEvent': void
            'App\Program\Message\ProgramAssignmentCreatedEvent': void
            'App\Program\Message\ProgramAssignmentDeletedEvent': void
            'App\Program\Message\ProgramAssignmentExpiredEvent': void
            'App\Program\Message\ProgramAssignmentUpdatedEvent': void

            'App\Subscription\Message\SubscriptionApprovedEvent': subscription
            'App\Subscription\Message\SubscriptionRejectedEvent': subscription
            'App\Subscription\Message\SubscriptionCreatedEvent': subscription

            'App\Vendor\Message\VendorBankAccountCreatedEvent': payment
            'App\Vendor\Message\VendorBankAccountUpdatedEvent': payment
            'App\Vendor\Message\VendorBankAccountDeletedEvent': void

            'Symfony\Component\Mailer\Messenger\SendEmailMessage': email
