nelmio_api_doc:
    documentation:
        info:
            title: 99 Trainer API
            version: 0.0.1
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/customer
    models:
        use_jms: false
        names:
            - { alias: Customer, type: App\Customer\Dto\CustomerDto }
