nelmio_api_doc:
    documentation:
        info:
            title: uFit API
            version: 0.0.1
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/currencies
            - ^/customers
            - ^/measurement_types
            - ^/vendors
            - ^/subscriptions
            - ^/questionnaires
    models:
        use_jms: false
        names:
            - { alias: Currency, type: App\Core\Dto\CurrencyDto }
            - { alias: Customer, type: App\Customer\Dto\CustomerDto }
            - { alias: CustomerMeasurement, type: App\Customer\Dto\CustomerMeasurementDto }
            - { alias: CustomerMeasurementItem, type: App\Customer\Dto\CustomerMeasurementItemDto }
            - { alias: CustomerPhoto, type: App\Customer\Dto\CustomerPhotoDto }
            - { alias: MeasurementType, type: App\Customer\Dto\MeasurementTypeDto }
            - { alias: Program, type: App\Program\Dto\ProgramDto }
            - { alias: ProgramAsset, type: App\Program\Dto\ProgramAssetDto }
            - { alias: ProgramAssignment, type: App\Program\Dto\ProgramAssignmentDto }
            - { alias: Vendor, type: App\Vendor\Dto\VendorDto }
            - { alias: VendorPlan, type: App\Vendor\Dto\VendorPlanDto }
            - { alias: Subscription, type: App\Subscription\Dto\SubscriptionDto }
            - { alias: Questionnaire, type: App\Vendor\Dto\QuestionnaireDto }
            - { alias: Question, type: App\Vendor\Dto\QuestionDto }
