nelmio_api_doc:
    documentation:
        info:
            title: uFit API
            version: 0.0.1
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/currencies
            - ^/customers
            - ^/vendors
            - ^/subscriptions
    models:
        use_jms: false
        names:
            - { alias: Currency, type: App\Core\Dto\CurrencyDto }
            - { alias: Customer, type: App\Customer\Dto\CustomerDto }
            - { alias: Vendor, type: App\Vendor\Dto\VendorDto }
            - { alias: VendorPlan, type: App\Vendor\Dto\VendorPlanDto }
            - { alias: Subscription, type: App\Subscription\Dto\SubscriptionDto }
