nelmio_api_doc:
    documentation:
        info:
            title: uFit API
            version: 0.0.1
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/currencies
            - ^/customers
            - ^/measure_types
            - ^/vendors
            - ^/subscriptions
            - ^/questionnaires
    models:
        use_jms: false
        names:
            - { alias: Currency, type: App\Core\Dto\CurrencyDto }
            - { alias: Customer, type: App\Customer\Dto\CustomerDto }
            - { alias: CustomerMeasure, type: App\Customer\Dto\CustomerMeasureDto }
#            - { alias: CustomerMeasureItem, type: App\Customer\Dto\CustomerMeasureItemDto }
            - { alias: MeasureType, type: App\Customer\Dto\MeasureTypeDto }
            - { alias: Vendor, type: App\Vendor\Dto\VendorDto }
            - { alias: VendorPlan, type: App\Vendor\Dto\VendorPlanDto }
            - { alias: Subscription, type: App\Subscription\Dto\SubscriptionDto }
            - { alias: Questionnaire, type: App\Vendor\Dto\QuestionnaireDto }
            - { alias: Question, type: App\Vendor\Dto\QuestionDto }
