nelmio_api_doc:
    documentation:
        info:
            title: uFit API
            version: 0.0.1
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/currencies
            - ^/customers
            - ^/measurement_types
            - ^/payments
            - ^/payment_methods
            - ^/questionnaires
            - ^/subscriptions
            - ^/vendors
            - ^/timezones
    models:
        use_jms: false
        names:
            - { alias: Currency, type: App\Localization\Dto\CurrencyDto }
            - { alias: Customer, type: App\Customer\Dto\CustomerDto }
            - { alias: CustomerMeasurement, type: App\Customer\Dto\CustomerMeasurementDto }
            - { alias: CustomerMeasurementItem, type: App\Customer\Dto\CustomerMeasurementItemDto }
            - { alias: CustomerPhoto, type: App\Customer\Dto\CustomerPhotoDto }
            - { alias: Invoice, type: App\Payment\Dto\InvoiceDto }
            - { alias: MeasurementType, type: App\Customer\Dto\MeasurementTypeDto }
            - { alias: Payment, type: App\Payment\Dto\PaymentDto }
            - { alias: PaymentMethod, type: App\Payment\Dto\PaymentMethodDto }
            - { alias: Program, type: App\Program\Dto\ProgramDto }
            - { alias: ProgramAsset, type: App\Program\Dto\ProgramAssetDto }
            - { alias: ProgramAssignment, type: App\Program\Dto\ProgramAssignmentDto }
            - { alias: Subscription, type: App\Subscription\Dto\SubscriptionDto }
            - { alias: SubscriptionCreate, type: App\Subscription\Dto\SubscriptionCreateDto }
            - { alias: Timezone, type: App\Localization\Dto\TimezoneDto }
            - { alias: Vendor, type: App\Vendor\Dto\VendorDto }
            - { alias: VendorBankAccount, type: App\Vendor\Dto\VendorBankAccountDto }
            - { alias: VendorPlan, type: App\Vendor\Dto\VendorPlanDto }
            - { alias: VendorSetting, type: App\Vendor\Dto\VendorSettingDto }
            - { alias: VendorStats, type: App\Vendor\Dto\VendorStatsDto }
            - { alias: VendorStatsReceivable, type: App\Vendor\Dto\VendorStatsReceivableDto }
            - { alias: VendorStatsRevenue, type: App\Vendor\Dto\VendorStatsRevenueDto }
            - { alias: VendorStatsSubscriptions, type: App\Vendor\Dto\VendorStatsSubscriptionsDto }
            - { alias: Questionnaire, type: App\Vendor\Dto\QuestionnaireDto }
            - { alias: Question, type: App\Vendor\Dto\QuestionDto }
