# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        default_adapter:
#            local:
#                directory: '%kernel.cache_dir%/flysystem'
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%customer_photo.s3_bucket%'
    filesystems:
        default_filesystem:
            adapter: default_adapter
            alias: League\Flysystem\FilesystemInterface

