# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
#        customer_photo_adapter:
#            local:
#                directory: '%kernel.cache_dir%/flysystem'
        customer_photo_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%s3.buckets.customer_photo%'
        program_asset_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%s3.buckets.program_asset%'
        vendor_photo_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%s3.buckets.vendor_photo%'

    filesystems:
        customer_photo_filesystem:
            adapter: customer_photo_adapter
            alias: customerPhotoFileSystem

        program_asset_filesystem:
            adapter: program_asset_adapter
            alias: programAssetFileSystem

        vendor_photo_filesystem:
            adapter: vendor_photo_adapter
            alias: vendorPhotoFileSystem
