version: '3.2'

services:
    php-fpm:
        container_name: ufit-api
        build: .
#        image: ufit-api-php-fpm
        env_file: .env.local
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            ENABLE_XDEBUG: 1
        expose:
            - 9000
        volumes:
            - ./docker/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - .:/app
    nginx:
        container_name: ufit-nginx
        image: nginx:alpine
        ports:
            - 80:80
        links:
            - php-fpm
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/app
    db:
        container_name: ufit-db
        image: postgres:12-alpine
        env_file: .env.local
        volumes:
            - db:/var/lib/postgresql/data

    rabbitmq:
        container_name: ufit-queue
        image: rabbitmq:3-alpine

    caddy:
        container_name: ufit-caddy
        image: "abiosoft/caddy:latest"
        volumes:
            - ./docker/caddy/certs:/root/certs
            - ./docker/caddy/Caddyfile:/etc/Caddyfile
        ports:
            - "443:2015"
        depends_on:
            - nginx

volumes:
    db:
