core_controllers:
    resource: '../../src/Core/Controller/'
    type: annotation

customer_controllers:
    resource: '../../src/Customer/Controller/'
    type: annotation

vendor_controllers:
    resource: '../../src/Vendor/Controller/'
    type: annotation

subscription_controllers:
    resource: '../../src/Subscription/Controller/'
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
