customer_controllers:
    resource: '../../src/Customer/Controller/'
    type: annotation

vendor_controllers:
    resource: '../../src/Vendor/Controller/'
    type: annotation

marketplace_controllers:
    resource: '../../src/Marketplace/Controller/'
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
