core_controllers:
    resource: '../../src/Core/Controller/'
    type: annotation

customer_controllers:
    resource: '../../src/Customer/Controller/'
    type: annotation

localization_controllers:
    resource: '../../src/Localization/Controller/'
    type: annotation

payment_controllers:
    resource: '../../src/Payment/Controller/'
    type: annotation

program_controllers:
    resource: '../../src/Program/Controller/'
    type: annotation

subscription_controllers:
    resource: '../../src/Subscription/Controller/'
    type: annotation

vendor_controllers:
    resource: '../../src/Vendor/Controller/'
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
