monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: info
            handler:      nested
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
            formatter: 'monolog.formatter.json'
        console:
            type:  console