# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    # This parameter defines the codes of the locales (languages) enabled in the application
    #    app_locales: ar|en|fr|de|es|cs|nl|ru|uk|ro|pt_BR|pl|it|ja|id|ca|sl|hr|zh_CN|bg|tr|lt
    app.locales: en|pt_BR
    app.notifications.email_sender: carlos@gonser.eu

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:               # defines the scalar arguments once and apply them to any service defined/created in this file
            $locales: '%app.locales%'
            $defaultLocale: '%locale%'
            $emailSender: '%app.notifications.email_sender%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    App\Core\:
        resource: '../src/Core/*'
        exclude: '../src/Core/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Core\Controller\:
        resource: '../src/Core/Controller'
        tags: ['controller.service_arguments']

    App\Customer\:
        resource: '../src/Customer/*'
        exclude: '../src/Customer/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Customer\Controller\:
        resource: '../src/Customer/Controller'
        tags: ['controller.service_arguments']

    App\Vendor\:
        resource: '../src/Vendor/*'
        exclude: '../src/Vendor/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Vendor\Controller\:
        resource: '../src/Vendor/Controller'
        tags: ['controller.service_arguments']

    App\Subscription\:
        resource: '../src/Subscription/*'
        exclude: '../src/Subscription/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Subscription\Controller\:
        resource: '../src/Subscription/Controller'
        tags: ['controller.service_arguments']

    #
    #    App\Blog\EventSubscriber\CommentNotificationSubscriber:
    #        $sender: '%app.notifications.email_sender%'

    App\Core\ArgumentResolver\UuidValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 500 }
